---
language: ruby
bundler_args: --without local_only
before_install: rm Gemfile.lock || true
rvm:
  - 2.3.1
  - 2.2.5
script: bundle exec rake test
env:
  - PUPPET_VERSION="~> 4.0.0"
  - PUPPET_VERSION="~> 4.1.0"
  - PUPPET_VERSION="~> 4.2.0"
  - PUPPET_VERSION="~> 4.3.0"
  - PUPPET_VERSION="~> 4.4.0"
  - PUPPET_VERSION="~> 4.5.0"
  - PUPPET_VERSION="~> 4.6.0"
  - PUPPET_VERSION="~> 4.7.0"
  - PUPPET_VERSION="~> 4.8.0"
notifications:
    email:
        recipients:
            - dfarrell@redhat.com
    on_success: change
    on_failure: change
